const countries = [
  { name: "United Kingdom", id: "UK" },
  { name: "United States of America", id: "USA" },
  { name: "New Zealand", id: "NZ" },
  { name: "Netherlands", id: "NL" },
  { name: "Russian Federation", id: "RF" },
  { name: "Slovenia", id: "SI" },
  { name: "Liechtenstein", id: "LI" },
  { name: "Romania", id: "RO" },
  { name: "Norway", id: "NO" },
  { name: "Turkey", id: "TR" },
  { name: "Japan", id: "JP" },
  { name: "Malta", id: "MT" },
  { name: "Portugal", id: "PT" },
  { name: "Slovakia", id: "SK" },
  { name: "Spain", id: "ES" },
  { name: "Sweden", id: "SE" },
  { name: "Latvia", id: "LV" },
  { name: "Poland", id: "PL" },
  { name: "Lithuania", id: "LT" },
  { name: "Luxembourg", id: "LU" },
  { name: "Switzerland", id: "CH" },
  { name: "Ukraine", id: "UA" },
  { name: "Australia", id: "AU" },
  { name: "Iceland", id: "IS" },
  { name: "Ireland", id: "IE" },
  { name: "Czech Republic", id: "CZ" },
  { name: "Canada", id: "CD" },
  { name: "Belgium", id: "BE" },
  { name: "Estonia", id: "EE" },
  { name: "Austria", id: "AT" },
  { name: "Hungary", id: "HU" },
  { name: "Italy", id: "IT" },
  { name: "Denmark", id: "DK" },
  { name: "European Union", id: "EU" },
  { name: "France", id: "FR" },
  { name: "Finland", id: "FI" },
  { name: "Greece", id: "GR" },
  { name: "Cyprus", id: "CY" },
  { name: "Germany", id: "DE" },
  { name: "Belarus", id: "BL" },
  { name: "Bulgaria", id: "BG" },
  { name: "Croatia", id: "HR" }
]

module.exports = countries